name = "cloudflare-backend"
main = "src/index.ts"
compatibility_date = "2026-03-01"

[[kv_namespaces]]
binding = "KV"
id = "695a2234a1704cf693385666f5ce902d"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "photos"

[[d1_databases]]
binding = "DB"
database_name = "photos-db"
database_id = "94b16b1f-ff69-4f23-b1d2-0df20febe2b3"

[vars]
GOOGLE_CLIENT_ID = "611505411727-94u34em16j7sd0rdigejmvfdgnjj67ma.apps.googleusercontent.com"
ALLOWED_EMAIL = "m.polkiewicz@gmail.com"
